dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env 
wallets: 
  from_key: ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_usd_price_feed: '0x2e25B53AFe79E69eAE06FB8D1433144f1D869c88' # account address
    verify: True
  development:
    verify: False